"use strict";

window.MaterialCatalog = [
  { id: "broken_shell", name: "欠けた甲殻", rank: "E", value: 20, category: "shell", prompts: ["small shell", "rough armor", "damaged plating", "weak organic frame"] },
  { id: "thin_membrane", name: "薄い飛膜", rank: "D", value: 45, category: "wing", prompts: ["thin insect wing", "fragile membrane", "light organic part"] },
  { id: "dry_nerve", name: "乾いた神経束", rank: "C", value: 60, category: "nerve", prompts: ["thin organic cable", "dry nerve fiber", "minor bio circuit"] },
  { id: "brittle_bone", name: "脆い骨片", rank: "E", value: 30, category: "bone", prompts: ["small bone shard", "brittle frame", "pale organic plate"] },
  { id: "aged_scale", name: "劣化した外骨", rank: "C", value: 75, category: "shell", prompts: ["aged exoskeleton", "worn plating", "medium organic armor"] },
  { id: "wilted_bloodfilm", name: "朽ちた血管膜", rank: "D", value: 35, category: "organ", prompts: ["thin red membrane", "withered bio film", "minor vascular mesh"] }
,
  { id: "dragon_heart", name: "ドラゴンハート", rank: "UR", rarity: "UR", value: 5000, category: "bossWeaponMaterial", materialRole: "weapon_core", prompts: ["dragon heart", "weapon core"] },
  { id: "abyss_eye", name: "アビスアイ", rank: "UR", rarity: "UR", value: 5000, category: "bossWeaponMaterial", materialRole: "weapon_core", prompts: ["abyss eye", "weapon core"] },
  { id: "titan_bone", name: "タイタンボーン", rank: "UR", rarity: "UR", value: 5000, category: "bossWeaponMaterial", materialRole: "weapon_core", prompts: ["titan bone", "weapon core"] },
  { id: "ancient_core", name: "エンシェントコア", rank: "UR", rarity: "UR", value: 5000, category: "bossWeaponMaterial", materialRole: "weapon_core", prompts: ["ancient core", "weapon core"] }];

window.EnemyCatalog = [
  { name: "小型甲殻獣", level: 6, hp: 980, maxHp: 980, atk: 118, def: 48, type: "甲殻", species: "beast", race: "beast", enemyType: "beast", drops: ["broken_shell", "brittle_bone"] },
  { name: "飛膜蟲", level: 9, hp: 1260, maxHp: 1260, atk: 146, def: 58, type: "飛行型", species: "insect", race: "insect", enemyType: "insect", drops: ["thin_membrane", "broken_shell", "wilted_bloodfilm"] },
  { name: "神経喰らい", level: 12, hp: 1580, maxHp: 1580, atk: 172, def: 66, type: "神経型", species: "beast", race: "beast", enemyType: "beast", drops: ["dry_nerve", "wilted_bloodfilm", "aged_scale"] }
];

window.GameState = {
  saveVersion: 4,
  maxOwnedMechs: 30,
  maxPartyMechs: 4,
  player: {
    id: "local_player",
    name: "名無しの探索者",
    rank: "E",
    exp: 0,
    money: 12450,
    currentFloor: 1,
    maxReachedFloor: 1,
    createdAt: "",
    updatedAt: ""
  },
  money: 12450,
  pilots: [
    { id: "tilia", name: "ティリア・ハーツ", gender: "female", rank: "A", classId: "ace", class: "エース", role: "戦闘指揮官", description: "アーク・クレイドルの戦闘指揮官。専用機フランベルジュを失い、序盤はレイのサーベリオン[S型]に搭乗する。", traitId: "overdrive_specialist", traitRank: "A", talents: [{ talentId: "overdrive_specialist", rank: 4 }], level: 1, exp: 0, skillPoints: 0, learnedSkills: ["ace_001"], appearanceId: "ace_female", hireCost: 0, hired: true, hair: "#d9dce2", skin: "#b99481" },
    { id: "ray", name: "レイ・クロード", gender: "male", rank: "B", classId: "striker", traitId: "size_m_specialist", traitRank: "B", talents: [{ talentId: "size_m_specialist", rank: 3 }], level: 1, exp: 0, skillPoints: 0, learnedSkills: ["striker_001"], appearanceId: "striker_male", hireCost: 1200, hired: true, hair: "#15181c", skin: "#9b725c", description: "近接戦闘が得意なストライカー。お調子者で猪突猛進な戦闘狂。" },
    { id: "sera", name: "セラ・ノクティス", gender: "female", rank: "B", classId: "gunner", traitId: "fuel_saver", traitRank: "B", talents: [{ talentId: "fuel_saver", rank: 3 }], level: 1, exp: 0, skillPoints: 0, learnedSkills: ["gunner_001"], appearanceId: "gunner_female", hireCost: 900, hired: true, hair: "#d7d9dd", skin: "#b99481", description: "冷静沈着なガンナー。突っ込み役。" },
    { id: "glen", name: "グレン・バルド", gender: "male", rank: "B", classId: "commander", traitId: "tag_command_specialist", traitRank: "B", talents: [{ talentId: "tag_command_specialist", rank: 3 }], level: 1, exp: 0, skillPoints: 0, learnedSkills: ["commander_001"], appearanceId: "commander_male", hireCost: 800, hired: true, hair: "#8b4f2f", skin: "#a56e4e", description: "副官。イケメンだが、いつもダジャレを考えている。" }
  ],
  mechs: [
    {
      id: "sabellion_s",
      name: "サーベリオン[S型]",
      rank: "R",
      level: 1,
      exp: 0,
      nextExp: 100,
      size: "中型",
      tags: ["general", "melee"],
      stats: { hp: 1180, pp: 38, sAtk: 360, mAtk: 250, lAtk: 285, sDef: 255, mDef: 220, lDef: 235, speed: 330 },
      mainWeapon: { id: "sabellion_s_main_weapon", name: "高周波ブレード", rank: "R", weaponType: "melee", element: "none", power: 48, ppCost: 0, overdrive: null },
      subWeapons: [],
      optionSlots: 1,
      equippedOptions: [],
      options: [],
      hp: 1180,
      maxHp: 1180,
      atk: 360,
      def: 255,
      mobility: 330,
      fuelCostRate: 1.0,
      traits: ["エース調整", "近接戦闘用量産機"],
      pilotId: "tilia",
      unique: false,
      parts: { rightArm: "高周波ブレード", leftArm: "標準マニピュレータ", back: "標準スラスター", support: "エース調整OS" },
      weaponType: "melee",
      description: "エース用にカスタマイズされた近接戦闘用量産機。ティリアの専用機フランベルジュに比べると性能は格段に劣る。元はレイの機体。"
    },
    {
      id: "sabellion_a",
      name: "サーベリオン[A型]",
      rank: "N",
      level: 1,
      exp: 0,
      nextExp: 100,
      size: "中型",
      tags: ["general", "melee"],
      stats: { hp: 1020, pp: 34, sAtk: 310, mAtk: 230, lAtk: 250, sDef: 232, mDef: 204, lDef: 210, speed: 300 },
      mainWeapon: { id: "sabellion_a_main_weapon", name: "量産型ブレード", rank: "N", weaponType: "melee", element: "none", power: 38, ppCost: 0, overdrive: null },
      subWeapons: [],
      optionSlots: 1,
      equippedOptions: [],
      options: [],
      hp: 1020,
      maxHp: 1020,
      atk: 310,
      def: 232,
      mobility: 300,
      fuelCostRate: 1.0,
      traits: ["近接戦闘用量産機", "標準出力"],
      pilotId: "ray",
      unique: false,
      parts: { rightArm: "量産型ブレード", leftArm: "標準マニピュレータ", back: "標準スラスター", support: "標準火器管制" },
      weaponType: "melee",
      description: "近接戦闘に特化した量産機。レイは本来のS型をティリアに譲ったことに不満を抱いている。"
    },
    {
      id: "honeybee_b",
      name: "ハニービー[B型]",
      rank: "N",
      level: 1,
      exp: 0,
      nextExp: 100,
      size: "小型",
      tags: ["general", "ranged", "supply"],
      stats: { hp: 900, pp: 42, sAtk: 220, mAtk: 255, lAtk: 318, sDef: 190, mDef: 218, lDef: 230, speed: 340 },
      mainWeapon: { id: "honeybee_b_main_weapon", name: "簡易スナイパーライフル", rank: "N", weaponType: "ranged", element: "none", power: 40, ppCost: 2, overdrive: null },
      subWeapons: [],
      optionSlots: 1,
      equippedOptions: [],
      options: [],
      hp: 900,
      maxHp: 900,
      atk: 318,
      def: 230,
      mobility: 340,
      fuelCostRate: 0.9,
      traits: ["補給用フレーム", "遠距離対応"],
      pilotId: "sera",
      unique: false,
      parts: { rightArm: "簡易スナイパーライフル", leftArm: "補給アーム", back: "軽量コンテナ", support: "遠距離照準補助" },
      weaponType: "ranged",
      description: "本来は補給用の機体。セラのガンナー適性とは合わないが、スナイパーライフルを装備しており遠距離攻撃は可能。"
    }
  ],
  partyMechIds: ["sabellion_s", "sabellion_a", "honeybee_b", null],
  pendingGeneratedMech: null,
  materials: { broken_shell: 12, thin_membrane: 8, dry_nerve: 6, brittle_bone: 10 },
  baseInventory: {
    materials: { broken_shell: 12, thin_membrane: 8, dry_nerve: 6, brittle_bone: 10 },
    materialLimit: 9999
  },
  exploreInventory: {
    materials: {},
    slotLimit: 100
  },
  deathLocation: null,
  inventory: {
    items: { repair_kit_s: 2, ether_pack_s: 1 },
    options: {},
    weapons: {},
    cores: { core_r: 1, core_sr: 1 }
  },
  market: {
    listings: []
  },
  scenario: {
    active: false,
    currentId: null,
    index: 0,
    returnScene: "bar",
    seen: {}
  },
  exploration: {
    fuel: 100,
    maxFuel: 100,
    currentFloor: 1,
    temporaryMaterials: {},
    isExploring: false
  },
  ship: {
    driftDay: 1,
    food: 100,
    medicine: 30,
    fuel: 300,
    materials: 0,
    energy: 100,
    resourceCaps: { food: 500, medicine: 200, fuel: 1000, materials: 9999 },
    foodProduction: 0,
    medicineProduction: 0,
    energyProduction: 0,
    foodCostReduction: 0,
    medicineCostReduction: 0,
    energyCostReduction: 0,
    fuelCostReduction: 0,
    explorationFuelCostReduction: 0,
    foodStorageStability: 0,
    materialYieldBonus: 0,
    repairCostReduction: 0,
    mechCostReduction: 0,
    infectionRecoveryReduction: 0,
    infectionRateReduction: 0,
    medicineRecoveryBonus: 0,
    diseaseRecoveryReduction: 0,
    shortRecoveryReduction: 0,
    dailyTrainingExp: 0,
    reservePilotExpRate: 0,
    battleExpBonus: 0,
    sortieBuffChance: 0,
    sortieBuffPower: 0,
    pilotBaseBonus: 0,
    weaponLevelBonus: 0,
    generatedMechLevelBonus: 0,
    machineEnhanceExpBonus: 0,
    hangarBonus: 0,
    pilotCapacityBonus: 0,
    lifeSupportCostReduction: 0,
    facilities: {
      foodStorage: 0,
      engine: 0,
      lifeSupport: 0,
      tacticalSupport: 0,
      mechDevelopment: 0,
      fuelMaintenance: 0,
      fuelEfficiency: 0,
      foodMaintenance: 0,
      materialYield: 0,
      repairEfficiency: 0,
      medicalRecovery: 0,
      infectionControl: 0,
      medicineSupply: 0,
      foodPlant: 0,
      wasteProcessor: 0,
      mealQuality: 0,
      satisfyingMeals: 0,
      shortRecovery: 0,
      diseaseTreatment: 0,
      medicalPlant: 0,
      medicalEfficiency: 0,
      weaponDevelopment: 0,
      frameDevelopment: 0,
      maintenanceKnowhow: 0,
      materialSaving: 0,
      learningComputer: 0,
      sleepLearning: 0,
      simulatorTraining: 0,
      pilotBaseTraining: 0,
      hangarExpansion: 0,
      cryosleepWard: 0,
      warehouseExpansion: 0,
      lifeSupportSystem: 0
    },
    einTrace: 0,
    specialists: [],
    vesselName: "アーク・クレイドル",
    vesselNameEn: "ARK CRADLE",
    mechTypeName: "ヴァリアント・フレーム",
    mechTypeNameEn: "VARIANT FRAME",
    mechTypeShortName: "フレーム"
  },
  // TODO: 序盤会話イベント予定: 覚醒、ブリッジ初回、初回探索前、エリア5到達、ボス撃破後、フレーム生成初回、揺り篭ユニット回収後。
  storyCharacters: [
    { id: "miranda", name: "ミランダ・ワイズマン", role: "艦長", description: "新任艦長。経験が浅く頼りない。" },
    { id: "dou", name: "ドゥ", role: "予備の人型AI", description: "従順だが指示待ち気味。" }
  ],
  runMaterials: {},
  currentScene: "bar",
  tavernCandidates: [],
  masters: { classes: [], traits: [], talents: [], skills: [], pilotNames: [], mechs: [], mechTraits: [], overdrives: [] },
  fuel: 100,
  floor: 3,
  maxFloor: 20,
  selectedPlanetId: null,
  quest: {
    selectedPlanetId: null,
    currentPlanetId: null,
    planetId: null,
    planetName: "",
    floor: 1,
    size: "XS",
    terrain: "plain",
    width: 4,
    height: 4,
    map: [],
    player: { x: 0, y: 0, direction: "N" },
    fuel: 100,
    maxFuel: 100,
    discovered: {},
    foundStairs: false,
    log: [],
    battleTacticId: "standard",
    pendingFieldEnemy: null,
    fieldEnemies: [],
    nextFieldEnemySerial: 1
  },
  exploredSteps: 0,
  distance: 142,
  selectedMechId: "sabellion_s",
  nextMechSerial: 1,
  nextWeaponSerial: 1,
  selectedMaterialId: "broken_shell",
  synthesisSlots: [],
  synthSerial: 1,
  battle: null,
  logs: {
    bar: ["艦長: ブリッジへようこそ。ユグドラシルは現在、漂流状態です。"],
    quest: ["3Fに到達した……"],
    battle: [],
    synthesis: ["培養炉を起動。素材スロットは最大5枠。"]
  }
};

window.RankConfig = {
  ranks: ["E", "D", "C", "B", "A", "S"],
  hireCosts: { E: 300, D: 600, C: 1200, B: 2500, A: 5000, S: 10000 },
  rankWeights: [
    { rank: "E", weight: 30 },
    { rank: "D", weight: 25 },
    { rank: "C", weight: 20 },
    { rank: "B", weight: 15 },
    { rank: "A", weight: 8 },
    { rank: "S", weight: 2 }
  ]
};


